// <auto-generated />
namespace MarketplaceV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nullabledatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullabledatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "202005241948556_nullable-datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
